# Generated by Django 5.2.8 on 2025-11-22 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='users.doctorprofile')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('doctor', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('consultation_type', models.CharField(choices=[('VIDEO', 'Video Call'), ('AUDIO_ONLY', 'Audio Only'), ('MESSAGING', 'Asynchronous Messaging')], default='VIDEO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='users.doctorprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='users.patientprofile')),
                ('availability_slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='consultations.doctoravailabilityslot')),
            ],
        ),
    ]
